### ISSUE TITLE
Problems with project.pbxproj

### ISSUE THREAD

**Issue by drisme** [iyegoroff/make-react-native-package#1]
Hi, first of all thanks for creating this tool! I was looking everywhere for a tool that could create an RN library that uses Swift.

I forked the project to remove the github links, since I'm using gitlab for this project. When trying to load xcode I get the error: 
`The project ´...’ is damaged and cannot be opened due to a parse error. Examine the project file for invalid edits or unresolved source control conflicts.`

Upon closer examination project.pbxproj is empty. Is this intended?

Perhaps you could look at my fork. In general I think it might be good to make github optional, since not everyone will need this feature.

Thanks for your all your efforts! :)

**Comment by iyegoroff** [comment]
Hi, @drisme.

> When trying to load xcode I get the error:
The project ´...’ is damaged and cannot be opened due to a parse error. Examine the project file for invalid edits or unresolved source control conflicts.
Upon closer examination project.pbxproj is empty. Is this intended?

Yes, this file is not intended to be opened - its presence required by some RN internals. To work in Xcode you have to open `.xcworkspace` file from `./example/ios/` folder, just like when developing ordinary RN app.

> In general I think it might be good to make github optional, since not everyone will need this feature.

`githubUsername` is a required identifier - please look how it is used inside template folder - https://github.com/iyegoroff/make-react-native-package/search?p=1&q=githubUsername&unscoped_q=githubUsername

Despite not everyone uses github, I consider `githubUsername` option a good default and its removal will increase amount of boring work with various `.md` files for myself and other potential users. If your package is not OSS - it is completely ok to use any identifier as `githubUsername`.
